// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKLZcSWHckRAWp_gSqKxd2ZfFlH69H0I0',
    appId: '1:582977201331:web:26fdba66b0260ca1edfcc6',
    messagingSenderId: '582977201331',
    projectId: 'devkazi',
    authDomain: 'devkazi.firebaseapp.com',
    storageBucket: 'devkazi.firebasestorage.app',
    measurementId: 'G-YXVWJJ84C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7AdKzZEHxNFGj9egJSK5_ka4ljFJ4b_I',
    appId: '1:582977201331:android:b6a7797bf3de51b2edfcc6',
    messagingSenderId: '582977201331',
    projectId: 'devkazi',
    storageBucket: 'devkazi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0prBuYZwkg74d30VESlRCFHxe3bjrerM',
    appId: '1:582977201331:ios:781e00deab0ccc61edfcc6',
    messagingSenderId: '582977201331',
    projectId: 'devkazi',
    storageBucket: 'devkazi.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0prBuYZwkg74d30VESlRCFHxe3bjrerM',
    appId: '1:582977201331:ios:781e00deab0ccc61edfcc6',
    messagingSenderId: '582977201331',
    projectId: 'devkazi',
    storageBucket: 'devkazi.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKLZcSWHckRAWp_gSqKxd2ZfFlH69H0I0',
    appId: '1:582977201331:web:2df46bc249556dc6edfcc6',
    messagingSenderId: '582977201331',
    projectId: 'devkazi',
    authDomain: 'devkazi.firebaseapp.com',
    storageBucket: 'devkazi.firebasestorage.app',
    measurementId: 'G-XY2PRYKYZ8',
  );
}
